# Site settings
title: luosw Online
SEOTitle: luosw Online
header-img: img/web-bg.jpg
email: luosw@luosw.cc
description: "Every failure is leading towards success."
keyword: "luosw, luosw Web, Siwei"
url: "http://gitluosw.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/gitluosw/luosw" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "STAY HUNGRY, STAY FOOLISH"
sidebar-avatar: /img/about-luosw.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# 显示中间第一行字
showMiddleLine1: false
# 显示中间第二行字
showMiddleLine2: false
# 小朋友
xiaopengyou: true

# SNS settings
RSS: false
# weibo_username:     luosw
#zhihu_username:     luosw
#github_username:    luosw
#facebook_username:  luosw
#jianshu_username:   luosw
#twitter_username:   luosw




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: luosw

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 815d3b85ed8d6c42a0cc                            #生成的clientID
  clientSecret: 3881a5b75c115a863ecd8d7084e58ae266e628db    #生成的clientSecret
  repo: luosw    #仓库名称
  owner: gitluosw    #github用户名
  admin: gitluosw
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f8033ab2fcba79c029fbdfe169c4fa49

# Google Analytics
ga_track_id: 'UA-G-QD5MGCCS2X'            # Format: UA-xxxxxx-xx
ga_domain: luosw.cc               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Google Scholar",
        href: "https://scholar.google.com/"
    },{
        title: "NetEase CloudMusic",
        href: "https://music.163.com/"        
    },{
        title: "Github",
        href: "https://github.com/"        
    },{
        title: "luosw Online",
        href: "http://luosw.cc"
    }
]
